# Generated by Django 4.0 on 2022-08-09 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cv_skill_referee_profile_experince_academic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academic',
            old_name='e_award',
            new_name='a_award',
        ),
        migrations.RenameField(
            model_name='academic',
            old_name='e_year',
            new_name='a_year',
        ),
    ]
