# Generated by Django 4.0 on 2022-08-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_street_profile_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avator',
            field=models.FileField(default='profile/avator.png', null=True, upload_to='profile/'),
        ),
    ]
